version: '3.5'



networks:
  fronted_net:
    external: true
    name: bridge_between_frontend_backend


services:
  frontend_sl:
    container_name: frontend-sl
    build:
      context: ./frontend_sl # but the source path that we will search about docker image from it
      dockerfile: development.Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=frontend_sl.settings.development
      - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - static_vol:/app/static # /app: workdir that we created in docker image and move our files in it
      - media_vol:/app/media
    networks:
      - fronted_net




volumes:
  static_vol:
  media_vol:
